In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [5]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model = Sequential()
model.add(Dense(2, input_dim=2, activation='linear'))
model.add(Dense(1, activation='linear'))

d:\Deep Learning\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.get_weights()

[array([[-0.04706657,  0.56164   ],
        [ 0.09744954, -0.05228937]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.4276337],
        [ 1.1495816]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32), 
             np.array([0.0,0.0], dtype=np.float32), 
             np.array([[0.1],[0.1]], dtype=np.float32), 
             np.array([0.0], dtype=np.float32)]

In [10]:
model.set_weights(new_weights)

In [11]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='mean_squared_error')

In [14]:
model.fit(df.iloc[:,0:-1].values, df['lpa'], epochs=75, verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 27.8968 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 27.5588
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 27.2439
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.8924 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.5448 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.2095 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25.8259 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 25.4359
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.0398 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.6490 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.2139 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 23.8252
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.3800 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 22.9078 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.4467
Epoch 16/75
4/4 ━━━

In [15]:
model.get_weights()

[array([[0.37364176, 0.37364176],
        [0.3657945 , 0.3657945 ]], dtype=float32),
 array([0.27243388, 0.27243388], dtype=float32),
 array([[0.37305558],
        [0.37305558]], dtype=float32),
 array([0.20494762], dtype=float32)]